add book to main
frozen-valley/frozen-valley pull request #10
Opened 2024-11-13 16:16 UTC by dean-rakic

2024-11-13 16:21 UTC, savipauk requested changes

2024-11-13 16:21 UTC, savipauk commented on book/pageTurner.gd
> +var is_open = false
dynamically typed

2024-12-10 00:25 UTC, marinprusac commented
Would be nice to have this resolved very soon. I helped with resolving conflicts. Only dynamic typing left to fix.

2024-12-10 14:40 UTC, savipauk approved these changes

2024-12-10 14:41 UTC, merged