added Tilemap, house and fox
frozen-valley/frozen-valley pull request #12
Opened 2024-12-10 16:40 UTC by dean-rakic

- implemented tilemap
- added house scene with dissapearing front
- added fox item

2024-12-10 16:50 UTC, marinprusac requested changes
There's some redundant asset importing among other things.
We should organize our artwork a little better so it doesn't get cluttered.

2024-12-10 16:50 UTC, marinprusac commented on inventory/inv_scripts/inventory_slot.gd
> +				item_visual.scale = Vector2(0.075, 0.075)
Number of indentations?

2024-12-10 16:50 UTC, marinprusac commented on scenes/area_2d.gd
Surely there's a better way to name this script?

2024-12-10 16:50 UTC, marinprusac commented on sprites/Axe.png
We already have an axe.png in sprites/misc.

2024-12-10 16:50 UTC, marinprusac commented on sprites/Debries.png.import
We already have a debris.png in sprites/misc.

2024-12-10 16:50 UTC, marinprusac commented on sprites/Key.png
We already have a key.png in sprites/misc.

2024-12-10 16:50 UTC, marinprusac commented on sprites/Plank.png
We already have a plank.png in sprites/misc.

2024-12-10 16:50 UTC, marinprusac commented on sprites/TileSet.png
Already have this in sprites/tiles. No?

2024-12-11 15:25 UTC, savipauk commented on scenes/area_2d.gd
+1 please rename

2024-12-11 20:16 UTC, marinprusac approved these changes

2024-12-11 20:16 UTC, merged