Add pathfinding to Partner
frozen-valley/frozen-valley pull request #33
Opened 2024-12-19 12:51 UTC by savipauk

Adds NavigationRegion2D and moves all static objects to be its child. Adds NavigationAgent2D to Partner and updates code to use pathfinding to move to the player. The partner still moves in 8 directions.

Changes:
- Tree collision shape from 16.03 to 17 px
- House walls are now a single polygon
- Makes House Z-index -1 which breaks some depth illusion
   - Should get fixed with #30 
- Fixes issue in player.gd where `move: Vector2` was reinitialized every physics process
- Changes map_level1

2024-12-19 18:47 UTC, marinprusac submitted a review, later dismissed
Didn't get to test it locally but seems good.

2025-01-06 18:59 UTC, marinprusac requested changes
Should resolve conflict and fix the facing direction of little sister.

2025-01-07 13:36 UTC, savipauk commented
> Should resolve conflict and fix the facing direction of little sister.

Fixed

2025-01-07 17:26 UTC, marinprusac approved these changes
It should all be working as intended now.

2025-01-08 10:45 UTC, merged